name: Release

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          npm add -g pnpm postject
          pnpm install
      - name: Build Windows
        run: pnpm build
      - name: Compress Windows Artifact
        run: Compress-Archive -Path dist/Git_Commit_Analytics_win.exe -DestinationPath Git_Commit_Analytics_win.zip
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: Git_Commit_Analytics_win.zip

  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          npm add -g pnpm postject
          pnpm install
      - name: Build macOS
        run: pnpm build
      - name: Compress macOS Artifact
        run: zip --junk-paths Git_Commit_Analytics_mac.zip dist/Git_Commit_Analytics_mac
      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mac-build
          path: Git_Commit_Analytics_mac.zip

  assets:
    runs-on: ubuntu-latest
    needs: [build-windows, build-mac]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-build
          path: dist/
      - name: Download macOS Artifact
        uses: actions/download-artifact@v4
        with:
          name: mac-build
          path: dist/
      - name: Prepare Assets
        run: |
          ls -lah dist/
      - name: Upload Final Assets
        uses: actions/upload-artifact@v4
        with:
          name: final-assets
          path: dist/

  release:
    runs-on: ubuntu-latest
    needs: [assets]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Final Assets
        uses: actions/download-artifact@v4
        with:
          name: final-assets
          path: dist/
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          npm add -g pnpm
          pnpm exec semantic-release
