name: Upload Release Asset

on: release

jobs:
  upload-release-asset:
    runs-on: ubuntu-latest
    steps:
      # 获取源码
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # 需要指定目标分支
          ref: main
      # 从 package.json 读取版本号
      - name: Get NPM Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      # 文件改名，加入版本号
      - name: Rename Files
        run: |
          mv Git_Commit_Analytics_win.zip Git_Commit_Analytics_v${{ steps.package-version.outputs.current-version}}_win.zip
          mv Git_Commit_Analytics_mac.zip Git_Commit_Analytics_v${{ steps.package-version.outputs.current-version}}_mac.zip
      # 上传 Win 版本的压缩包到 release
      - name: Upload To Release
        uses: JasonEtco/upload-to-release@master
        with:
          args: Git_Commit_Analytics_v${{ steps.package-version.outputs.current-version}}_win.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      # 删除 Win 版本的压缩包
      - name: Remove Files
        uses: JesseTG/rm@v1.0.2
        with:
          path: Git_Commit_Analytics_v${{ steps.package-version.outputs.current-version}}_win.zip
      # 上传 Mac 版本的压缩包到 release
      - name: Upload To Release
        uses: JasonEtco/upload-to-release@master
        with:
          args: Git_Commit_Analytics_v${{ steps.package-version.outputs.current-version}}_mac.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      # 删除 Mac 版本的压缩包
      - name: Remove Files
        uses: JesseTG/rm@v1.0.2
        with:
          path: Git_Commit_Analytics_v${{ steps.package-version.outputs.current-version}}_mac.zip
      # 提交代码
      - name: Save Changes
        run: |
          git config user.email "chengpeiquan@chengpeiquan.com"
          git config user.name "chengpeiquan"
          git add .
          git commit -m "chore: remove artifacts"
          git push
