name: Upload Release Asset

on:
  release:
    types: [published]

jobs:
  upload-release-asset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Fetch Latest Release Version
        id: fetch-latest-release
        uses: reloc8/action-latest-release-version@1.0.0
      - name: Rename Files with Version
        run: |
          mv Git_Commit_Analytics_win.zip Git_Commit_Analytics_${{ steps.fetch-latest-release.outputs.latest-release }}_win.zip
          mv Git_Commit_Analytics_mac.zip Git_Commit_Analytics_${{ steps.fetch-latest-release.outputs.latest-release }}_mac.zip
      - name: Upload Windows File To Release
        uses: JasonEtco/upload-to-release@master
        with:
          args: Git_Commit_Analytics_${{ steps.fetch-latest-release.outputs.latest-release }}_win.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: Remove Windows Files
        uses: JesseTG/rm@v1.0.2
        with:
          path: Git_Commit_Analytics_${{ steps.fetch-latest-release.outputs.latest-release }}_win.zip
      - name: Upload Mac File To Release
        uses: JasonEtco/upload-to-release@master
        with:
          args: Git_Commit_Analytics_${{ steps.fetch-latest-release.outputs.latest-release }}_mac.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: Remove Mac Files
        uses: JesseTG/rm@v1.0.2
        with:
          path: Git_Commit_Analytics_${{ steps.fetch-latest-release.outputs.latest-release }}_mac.zip
      - name: Commit Codes
        run: |
          git config user.email "chengpeiquan@chengpeiquan.com"
          git config user.name "chengpeiquan"
          git add .
          git commit -m "chore: remove artifacts"
          git push
